echo Ensuring Kivy is installed...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\install_kivy.ps1"

echo Ensuring libtorrent-python is installed...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\install_libtorrent.ps1"

echo Ensuring pyinstaller is installed...
C:\Kivy-1.8.0-py2.7-win32\kivy.bat -m pip install pyinstaller
