echo Ensuring Kivy is installed...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\SetupScripts\install_kivy.ps1"

echo Ensuring libtorrent-python is installed...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\SetupScripts\install_libtorrent.ps1"

echo Ensuring msysgit is installed...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\SetupScripts\install_msysgit.ps1"

echo Ensuring Notepad++ is installed...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\SetupScripts\install_notepadpp.ps1"

echo Ensuring pylzma is downloaded...
@powershell -NoProfile -ExecutionPolicy Bypass -File "c:\vagrant\SetupScripts\download_pylzma.ps1"

echo Ensuring pyinstaller and futures are installed...
C:\Kivy-1.8.0-py2.7-win32\kivy.bat -m pip install pyinstaller futures "c:\\vagrant\\Downloads\\pylzma-0.4.6-cp27-none-win32.whl"
